### ISSUE TITLE
SQL2012+ - InsertMany on IdentitySeed table not reliable 

### ISSUE THREAD

**Issue by tklingert** [jonwagner/Insight.Database#255] opened 2016-05-25 06:22 UTC
Hi,

i've got the following scenario:

```
Plan (PlanId [AutoIncrement])
    -> PlanPosition (PlanPositionId [AutoIncrement], PlanId) (1:n)
           -> PlanPositionLinkages (PlanPositionId, LinkageId) (0,1:n)
```

I'm using the 'AutoProc' feature:
- InsertList - Plans
  `connection.InsertList( this.GetCommandName( PlanTableName, AutoProc.ProcTypes.InsertMany ), plans, transaction: transaction.InnerTransaction );
  `
- I'm manually setting the PlanId of each PlanPosition to the newly generated ones by the insert statement:
  
  ```
        private IEnumerable<PlanPosition> SetForeignKeyAndReturnAllPositions( IReadOnlyList<Plan> plans )
        {
            foreach ( var plan in plans )
            {
                if ( plan.PlanPositions == null || plan.PlanPositions.Count == 0 )
                    continue;
                foreach ( var position in plan.PlanPositions )
                {
                    position.PlanId = plan.PlanId;
                    yield return position;
                }
            }
        }
  ```
- InsertList - PlanPositions
  `var rowCount = connection.InsertList( this.GetCommandName( PlanPositionTableName, AutoProc.ProcTypes.InsertMany ), this.SetForeignKeyAndReturnAllPositions( plans ), transaction: transaction.InnerTransaction ).Count( );`
- I'm manually setting the PlanPositionId of each Linkage according to (2.)

```
private IEnumerable<PlanPositionLinkage> SetForeignKeyAndReturnAllLinkages( IReadOnlyList<Plan> plans )
        {
            foreach ( var plan in plans )
            {
                if ( plan.PlanPositions == null || plan.PlanPositions.Count == 0 )
                    continue;
                foreach ( var position in plan.PlanPositions )
                {
                    if ( position.Linkages == null || position.Linkages.Count == 0 )
                        continue;
                    foreach ( var linkage in position.Linkages )
                    {
                        linkage.PlanPositionId = position.PlanPositionId;
                        yield return linkage;
                    }
                }
            }
        }
```
- BulkCopy - PlanPositionLinkages

`rowCount = connection.BulkCopy( PlanPositionLinkageTableName, this.SetForeignKeyAndReturnAllLinkages( plans ).ToArray( ), transaction: transaction.InnerTransaction );`

The source of the problem is:
`InsertList - Positions` maps the auto-generated PlanPositionId's in the wrong order.
I verified this by debugging and comparing the Id mapped to the plan position and a parallel database call to get the actual plan position for that id. And they differ.
=> The linkages are randomly associated to other plan positions, but not to those i've specified.

The weird thing is, if i use UpsertMany instead of InsertMany i get the expected result.

Kind regards

Thorsten

**Comment by tklingert** [comment] 2016-08-23 12:40
I did some more research on the issue:
[see: MSDN - OutputClause](https://msdn.microsoft.com/en-us/library/ms177564.aspx)
>The OUTPUT clause may be useful to retrieve the value of identity or computed columns after an INSERT or UPDATE operation.
>...
> There is no guarantee that the order in which the changes are applied to the table and the order in which the rows are inserted into the output table or table variable will correspond.

In a short, with the current version:
 - You shouldn't use the InsertMany on tables with auto-generated identity columns at all.  
   (The input order differs from the output one, therefore the identity value mapped back to the .Net object differs from the actual DB's one.)
 - UpsertMany seems to be a little bit more reliable:  
   `USING (SELECT *, [_insight_rownumber] = ROW_NUMBER() OVER (ORDER BY (SELECT 1)) FROM @Table)`  
      ...  
   `OUTPUT Inserted.[Id], s.[_insight_rownumber] INTO @T;
   SELECT 	[Id] FROM @T ORDER BY [_insight_rownumber]   
`  
   But in my sample test case (about 20000 rows, 3 foreign keys, some indexes) it fails too:  
   New empty database, same input, same sequential workflow => nearly everytime a different result :(

**Comment by kevinsea** [comment] 2016-08-24 14:48
Hi,

There is definitely a change in behavior with SQL 2012 where table variables no longer preserve the inserted order.  There is some discussion of this [here](http://www.sqlservercentral.com/Forums/Topic1466626-3077-1.aspx).  And [this](http://stackoverflow.com/questions/17550823/sql-row-number-adding-to-variable) provides some background on  ROW_NUMBER() that I found helpful.

So, SQL 2012 changes seem to be a big problem.  From the reading, it seems like we need to add an identity column to the table var ([_insight_rownumber] from above sounds good).  I assume its easy for you to take the AutoProc code and make it your own so you can update the output to sort on the var identity as a short term fix?

**Comment by tklingert** [comment] 2016-08-30 15:52
Hi,
thanks for the response and input :)

As I short-short-short term hoxfix i switched to single insert/upsert calls and neglected the performance impact. Obviously not a desirable solution.

I think it's not enough to add an identity (_insight_rownumber) to the table variable itself.
The Upsert-Many procedure already relies on such a logic and custom sorting on SQL-side and still isn't reliable in that case.
The output order needs to match extactly the input's one and the following trick doesn't work any more:
`[_insight_rownumber] = ROW_NUMBER() OVER (ORDER BY (SELECT 1)`

The only reliable option I see right now is:
  1. Add a '[_insight_rownumber]'-column to each user-defined table type,  
      if the table has an auto-increment identity column.
  2. Populate it reliable within the .Net-Code, before calling the procedure.
  3. Adjust the Auto-Proc InsertMany/UpsertMany code:  
      `SELECT ... FROM .. ORDER BY [_insight_rownumber]`

(2) requires changes within the Insight.Database codebase :/
If local AutoProc code changes would be sufficient, it wouldn't be such a big issue.

Kind regards
Thorsten

**Comment by kevinsea** [comment] 2016-08-30 18:35
> I think it's not enough to add an identity (_insight_rownumber) to the table variable itself.
The Upsert-Many procedure already relies on such a logic and custom sorting on SQL-side and still isn't reliable in that case.

The current code is doing the ordering after the data is in the table relying on the natural read order which is not guaranteed.  I believe a identity column in the table var would preserve order as provided from insight as it would be set on write rather than on read,  It would be great if you could try that out as it would help inform the best way to systematically fix it.

**Comment by jonwagner** [comment] 2016-08-31 03:24
Yeah, this is a nasty nasty inconsistency that the SQL guys should fix for us as an option to enable.

Last time I thought through the problem, I couldn't think of any easy ways to solve it. :(

Since SQL doesn't guarantee the return order, we'd have to match the IDs back to the right records. Even if we did a match on all fields, if you ever sent up two identical rows, you'd have to deal with the collisions. It would work but it would be hard to implement.

I think there's a lot of value in fixing this but it will be a lot of effort.

**Comment by kevinsea** [comment] 2016-09-01 03:51
Here is my thinking on the solution

- The identity on the table var will preserve the the order of the rows from insight (identities are assigned on the way in)  Let's call that identity column _insight_rownumber.

- Then, if the insert was written with an order by, eg

    insert mytable (col1, col2) Select col1, col2 from @tablevar ORDER by _insight_rownumber.

then the assignment of the ID of mytable will be assigned in the same order as _insight_rownumber.  (see point #4 from https://blogs.msdn.microsoft.com/sqltips/2005/07/20/ordering-guarantees-in-sql-server/ ...hopefully still true)

Therefore, sorting inserted.* by ID will be in the same order as provided from insight. 

@tklingert if you provide your insert proc, the corresponding table var and a create for your table, I think I can give you a proc that will pass your test.

**Comment by jonwagner** [comment] 2016-09-01 13:16
This sounds familiar. Didn't I do that at one point? _sigh_ memory failing...

**Comment by tklingert** [comment] 2016-09-02 12:01
@kevinsea
thanks, but I'm not sure if i understand you right.
Where do you want to add the _insight_rownumber identity column and how do you want to populate it ?

Quick sample:
```
CREATE TABLE [dbo].[Sample]
(
  [SampleId] [int] IDENTITY(1,1) NOT NULL,
  [SampleValue] [nvarchar] (255) NOT NULL,
  [RowVersion] [timestamp] NOT NULL,
  PRIMARY KEY([SampleId] ASC)
)
```
current  'InsertMany':

```
CREATE PROCEDURE [dbo].[Samples_Insert] (@Sample [dbo].[SampleTable] READONLY)
AS
DECLARE @T TABLE(
[SampleId] int,
[RowVersion] binary(8))

INSERT INTO [dbo].[Sample]
(
	[SampleValue]
)
OUTPUT
	Inserted.[SampleId],
	Inserted.[RowVersion]
INTO @T
SELECT
	[SampleValue]
FROM @Sample
SELECT * FROM @T
```
current  'UpsertMany':
```
CREATE PROCEDURE [dbo].[Samples_Upsert] (@Sample [dbo].[SampleTable] READONLY)
AS
DECLARE @T TABLE(
[SampleId] int,
[RowVersion] binary(8),
[_insight_rownumber] [int]
)

MERGE INTO [dbo].[Sample] AS t
USING (SELECT *, [_insight_rownumber] = ROW_NUMBER() OVER (ORDER BY (SELECT 1)) FROM @Sample) AS s
ON
(
	t.[SampleId] = s.[SampleId]
)
WHEN MATCHED THEN UPDATE SET
	t.[SampleValue] = s.[SampleValue]
WHEN NOT MATCHED BY TARGET THEN INSERT
(
	[SampleValue]
)
VALUES
(
	s.[SampleValue]
)
OUTPUT
	Inserted.[SampleId],
	Inserted.[RowVersion]
, s.[_insight_rownumber]
INTO @T
;
SELECT 
	[SampleId],
	[RowVersion]
FROM @T ORDER BY [_insight_rownumber]

```
You can't populate the [_insight_rownumber] on the select statement, since the ROW_NUMBER() trick doesn't work any more:
`[_insight_rownumber] = ROW_NUMBER() OVER (ORDER BY (SELECT 1)`
=> you need an identity write first in order to preserve the actual input order that way, right ?

So it's something like a double insert ?:
```
CREATE PROCEDURE [dbo].[Samples_Insert] (@Sample [dbo].[SampleTable] READONLY)
AS
DECLARE @DummyToPreserveOrder TABLE(
[_insight_rownumber] [int] IDENTITY(1,1),
[SampleValue] [nvarchar] (255) NOT NULL,
PRIMARY KEY([_insight_rownumber]))

DECLARE @T TABLE(
[SampleId] int,
[RowVersion] binary(8))

-- generate [_insight_rownumber] on write in order to preserve the order
INSERT INTO @DummyToPreserveOrder
(
	[SampleValue]
)
	SELECT
		[SampleValue]
	FROM @Sample
	-- Without ORDER BY, don't we run into the same issue again ?

-- perform actual table insert
INSERT INTO [dbo].[Sample]
(
	[SampleValue]
)
OUTPUT
	Inserted.[SampleId],
	Inserted.[RowVersion]
INTO @T
SELECT
	[SampleValue]
FROM @DummyToPreserveOrder
ORDER BY [_insight_rownumber]  -- keep SampleId identity ordering due to ordering guarantees in sql server

-- return the output in the same order as the input
SELECT * 
FROM @T
ORDER BY [SampleId]
```
But should raise the first insert the same issue again or am I missing something ?

**Comment by kevinsea** [comment] 2016-09-02 15:13
Here is what I'm thinking

	CREATE TABLE [dbo].[Sample]
	(
	  [SampleId] [int] IDENTITY(1,1) NOT NULL,
	  [SampleValue] [nvarchar] (255) NOT NULL,
	  [RowVersion] [timestamp] NOT NULL,
	  PRIMARY KEY([SampleId] ASC)
	)

	CREATE TYPE dbo.[SampleInsertArgs] AS TABLE
	(
	  [SampleValue] [nvarchar] (255) NOT NULL,
	  [RowVersion] [timestamp] NOT NULL,
	  [_insight_rownumber] [int] IDENTITY(1,1) NOT NULL  -- Gets set on row creation
	)
	GO


	Create PROCEDURE [dbo].[Samples_Insert] 
		@Sample dbo.SampleInsertArgs READONLY
	AS

		DECLARE @OutputRows TABLE(
			[SampleId] int,
			[RowVersion] binary(8))

		INSERT INTO [dbo].[Sample]
		(
			[SampleValue]
		)
			OUTPUT
				Inserted.[SampleId],
				Inserted.[RowVersion]
			INTO @OutputRows
		
			SELECT
				[SampleValue]
			FROM @Sample 
			Order By [_insight_rownumber]  -- retain the order as passed from insight
		
		SELECT * FROM @OutputRows order by [SampleId] -- [SampleId] representes order inserted
		
	GO

	-- run the test
	DECLARE @Samples AS dbo.SampleInsertArgs; 

	Insert into @Samples (SampleValue) Values ('10'), ('20'), ('30')

	-- verify [_insight_rownumber] represents order from insight
	Select * from @Samples  

	Exec [Samples_Insert] @Samples

**Comment by kevinsea** [comment] 2016-09-02 15:14
I think Upsert will require more work, but let's see if we can prove InsertMany works at scale this way.

**Comment by tklingert** [comment] 2016-09-03 13:09
Ah, I missed the user-defined table type.
That makes sense, i'll try it on monday and tell if it works.

Thanks !

**Comment by tklingert** [comment] 2016-09-06 09:48
Looks like the sample is too simple.
Boths ways, old and suggested, keep the order in that case.

Maybe the unwanted side effect is related to foreign keys and/or indicies.
I'll try to integrate it into my scenario...

**Comment by tklingert** [comment] 2016-09-06 10:51
I've created a fork and updated the AutoProc-code according to your suggestion:
https://github.com/tklingert/Insight.Database.Schema

In a short:
  * I can't verify whether it works or not without changes to the Insight.Database code as well.

MS-SQL doesn't support identity-insert on table variables:
> SqlException: INSERT into an identity column not allowed on table variables

Regarding to [sql-server-helper.com](http://www.sql-server-helper.com/error-messages/msg-1077.aspx), the workaround would be not to specify an explicit value for the [_insight_rownumber] column.
But that's in this case up to the caller, hence the Insight.Database library.

As another issue, the workaround would only cover tables with an identity column.
e.g. take a table with an Guid-Id column and a RowVersion timestamp: 
```
INSERT INTO [dbo].[Table]
(
...
)
OUTPUT
	Inserted.[RowVersion]
INTO @T
SELECT
...
FROM @Table
ORDER BY [_insight_rownumber]
SELECT * FROM @T
ORDER BY [Id] -- unable to retain the right order here
```

If a change to the Insight.Database code is required too, wouldn't it be the easiest and safest option to just populate the [_insight_rownumber]-column from the .Net code up on invocation ?

**Comment by kevinsea** [comment] 2016-09-06 13:56
Hi, 

Check out the example again, its working sql.  

There is no insert into the identity column.  The identity in the table var used only to maintain the order of the table var as passed to the proc.

**Comment by kevinsea** [comment] 2016-09-06 13:59
> Looks like the sample is too simple.  Boths ways, old and suggested, keep the order in that case.

I believe its only when there are many rows, parallel threads do the inserts, so yeah, I think your actual case is needed to prove it works.  (Everything I've read says it will).

**Comment by tklingert** [comment] 2016-09-06 16:38
Its working sql, yes.
I can execute it without any problems directly via SSMS.

But i'll end up with the previously mentioned SqlException, as soon as i call the procedure via the Insight.Database .Net library.
It looks like it provides a default value for the [_insight_rownumber] identity column.
=> ~=
```
DECLARE @Samples AS dbo.SampleInsertArgs; 
Insert into @Samples (SampleId, SampleValue) Values (0,'a'), (0,'b'), (0,'c')
```

**Comment by tklingert** [comment] 2016-09-06 16:47
I could fork and try to fix the issue there too, but the main problem I see right now is:
It would only fix half of the problem, the issue remains for tables without identity columns and some output columns like e.g. a Guid-Identity column and a generated RowVersion timestamp.

`I believe its only when there are many rows, parallel threads do the inserts, so yeah`
In my case, I can exclude parallel inserts on the same table.
(A single consumer thread writing to the database. The issue persists even if there is only one consumer connected).

**Comment by kevinsea** [comment] 2016-09-06 21:54
> It would only fix half of the problem, the issue remains for tables
without identity columns and some output columns like e.g. a Guid-Identity
column and a generated RowVersion timestamp.

Actually, doesn't the problem exists exclusively for server assigned pk's
where there is nothing to match on?  You can preserve passed order with the
table var and already knowing the PK already makes the output ordering
easier.  I'm not trying to avoid writing code to fix this, I'm just looking
for a way see if we have the right solution before going further.


> The issue persists even if there is only one consumer connected.

I think with very large writes, SQL divides up the the work of a single
consumer.  (Or, something about your case make it a reproducible problem.)

**Comment by kevinsea** [comment] 2016-09-13 11:56
@tklingert any interest in testing the method above to see if it definitely solves the issue?

**Comment by tklingert** [comment] 2016-09-16 05:46
sry for the late reply, we're close to a release, therefore time is running short atm.
Yes, i'll do for sure.
But after the release, since I need to modify the Insight.Database library too in order to reproduce or verify that the issue is gone within my scenario.
Around 27.09.

**Comment by kevinsea** [comment] 2016-09-16 10:36
No worries, looking forward to solving this once you have a bit more time.

**Comment by tklingert** [comment] 2017-02-11 15:00
Little update, i finally got some spare time.

_test setup:_
```sql
CREATE TABLE InsertByTableRNIdentityTable (ID [int] IDENTITY(1,1), ID2 [int] DEFAULT (2), Text [varchar](128), Value int)
GO
-- '_insight_rownumber' should get set on row creation
CREATE TYPE InsertByTableRNIdentityType AS TABLE (Text [varchar](128), Value int, [_insight_rownumber] INT IDENTITY(1,1) NOT NULL) 
GO
CREATE PROC InsertByTableRNIdentity(@OtherValue int, @Items [InsertByTableRNIdentityType] READONLY) AS 
	TRUNCATE TABLE InsertByTableTable
	DBCC CHECKIDENT ('InsertByTableRNIdentityTable', RESEED, 1)
	INSERT INTO InsertByTableRNIdentityTable (Text, Value)
		OUTPUT inserted.ID, inserted.ID2
		SELECT Text, @OtherValue FROM @Items
```
```csharp
[Test]
public void MultipleInsertShouldFillInIdentities_AutoIncrementInsightRownumber( )
{
	InsertRecord i = new InsertRecord( );
	InsertRecord i2 = new InsertRecord( );
	List<InsertRecord> list = new List<InsertRecord>( ) { i, i2 };

	var result = Connection( ).InsertList( "InsertByTableRNIdentity", list, new { OtherValue = 5, Items = list } );

	Assert.AreEqual( list, result );
	Assert.AreEqual( 1, i.Id );
	Assert.AreEqual( 2, i.Id2 );
	Assert.AreEqual( 2, i2.Id );
	Assert.AreEqual( 2, i2.Id2 );
}
```
_results:_
- No change on Insight.Database.SqlInsightDbProvider:
  - > INSERT into an identity column not allowed on table variables.
    > The data for table-valued parameter "@Items" doesn't conform to the table type of the parameter. SQL Server error is: 200, state: 7
- Adjust Insight.Database.SqlInsightDbProvider.GetTableTypeSchema:
  =~ Return a wrapped IDataReader which basically ignores the '_insight_rownumber' column,
        so that it doesn't get populated on client side
  - > Trying to pass a table-valued parameter with 2 column(s) where the corresponding user-defined table type requires 3 column(s).

So it looks like the auto-increment '_insight_rownumber' column needs to be populated on client side.
~= Remove identity(1,1) annotation and add a custom OBjectListDbDataReader implemention which populates the '_insight_rownumber' column accordingly.

Any better ideas ?

**Comment by tklingert** [comment] 2017-02-11 16:16
The latter at least works:

_**adjustments:**_
```csharp
internal class InsightRowNumberPopulatingObjectListDbDataReader : ObjectListDbDataReader
{
	private int _currentInsightRowNumber;
	private readonly int _insightRowNumberOrdinal;
	private readonly bool _hasInsightRowNumber;

	public InsightRowNumberPopulatingObjectListDbDataReader( ObjectReader objectReader, IEnumerable list )
		: base( objectReader, list )
	{
		this._insightRowNumberOrdinal = objectReader.GetOrdinal( "_insight_rownumber" );
		this._hasInsightRowNumber = this._insightRowNumberOrdinal >= 0;
	}
	public override bool Read( )
	{
		if ( base.Read( ) )
		{
			if (this._hasInsightRowNumber)
				Interlocked.Increment( ref this._currentInsightRowNumber );
			return true;
		}
		if ( this._hasInsightRowNumber )
			Interlocked.Exchange( ref this._currentInsightRowNumber, 0 );
		return false;
	}
	public override object GetValue( int ordinal )
	{
		if ( this._hasInsightRowNumber && ordinal == this._insightRowNumberOrdinal )
			return this._currentInsightRowNumber;
		return base.GetValue( ordinal );
	}
}
```
```csharp
...
	// create the structured parameter
	parameter.Value = new InsightRowNumberPopulatingObjectListDbDataReader( objectReader, list );
...
```
**_sample:_**
```sql
CREATE TABLE InsertByTableInsightRNTable (ID [int] IDENTITY(1,1), ID2 [int] DEFAULT (42), Text [varchar](128), Value int)
GO
CREATE TYPE InsertByTableInsightRNType AS TABLE (Text [varchar](128), Value int, [_insight_rownumber] INT NOT NULL)
GO
CREATE PROC InsertByTableInsightRN(@OtherValue int, @Items [InsertByTableInsightRNType] READONLY) AS 
    DECLARE @OutputRows TABLE(ID [int], ID2 [int])

	TRUNCATE TABLE InsertByTableInsightRNTable
	DBCC CHECKIDENT ('InsertByTableInsightRNTable', RESEED, 1)

	INSERT INTO InsertByTableInsightRNTable (Text, Value)
		OUTPUT inserted.ID, inserted.ID2
		INTO @OutputRows
		SELECT Text, [_insight_rownumber] FROM @Items
		ORDER BY [_insight_rownumber] -- retain the order as passed from insight

	SELECT o.ID, o.ID2, t.[Value] FROM @OutputRows as o
		INNER JOIN InsertByTableInsightRNTable as t -- only to return the [_insight_rownumber] passed in to the output again & verify it
			on o.Id = t.Id
	ORDER BY o.ID -- [Id] represents order inserted
GO
```
```csharp
[Test]
public void MultipleInsertShouldFillInIdentities_SupportsInsightRownumber( )
{
	InsertRecord i = new InsertRecord( );
	InsertRecord i2 = new InsertRecord( );
	List<InsertRecord> list = new List<InsertRecord>( ) { i, i2 };

	var result = Connection( ).InsertList( "InsertByTableInsightRN", list, new { OtherValue = 5, Items = list } );

	Assert.AreEqual( list, result );
	Assert.AreEqual( 1, i.Id );
	Assert.AreEqual( 42, i.Id2 );
	Assert.AreEqual( 1, i.Value ); // the procedure maps the provided [_insight_rownumber] value to this property
	Assert.AreEqual( 2, i2.Id );
	Assert.AreEqual( 42, i2.Id2 );
	Assert.AreEqual( 2, i2.Value ); // the procedure maps the provided [_insight_rownumber] value to this property
}
```

=> That way, at least InsertMany would work as expected again.
      UpsertMany is a different case though.

**Comment by jonwagner** [comment] 2017-06-06 01:26
6.0.0-alpha2 will have automatic support for _insight_rownumber in TVPs.

Going to go do another build of Insight.Database.Schema...

**Comment by jonwagner** [comment] 2017-06-09 20:02
6.0.0-alpha2 now supports TVPs with identity columns.
Insight.Database.Schema will have an update for the InsertMany/UpsertMany autoprocs so they automatically add a rownumber identity column.

**Closed** 2017-06-09 20:50 UTC
Labels: bug
