### ISSUE TITLE
Serializer not used on table parameter property types

### ISSUE THREAD

**Issue by roryprimrose** [jonwagner/Insight.Database#217] opened 2015-08-19 07:10 UTC
Serializers are used when reading unknown property types on classes from the database. However it looks like they are not used when sending a table parameter to a procedure.

I've created a fork with a test that proves this, but I'm having a lot of trouble debugging it to know where it is going wrong.

The failure is

```
System.InvalidCastException : Specified cast is not valid.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, ref Task task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, ref Task task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose(IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) in DBConnectionExtensions.cs: line 1459
   at Insight.Database.DBConnectionExtensions.Query(IDbConnection connection, String sql, Object parameters, IQueryReader`1 returns, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) in DBConnectionExtensions.cs: line 497
   at Insight.Database.DBConnectionExtensions.Query(IDbConnection connection, String sql, Object parameters, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) in DBConnectionExtensions.generated.cs: line 51
   at Insight.Tests.CustomSerializationTests.CustomSerializerSupportsTableParameters() in SerializationTests.cs: line 95
```

**Comment by roryprimrose** [comment] 2015-08-19 23:45
Repro is at https://github.com/roryprimrose/Insight.Database/commit/ab42ce1841b5c927530befe5ad2db5f33a1cf777

Interestingly, I can't get any debugger info for the proc call, just the initial command executions that get schema information. This has made it very difficult to solve this problem.

**Comment by jonwagner** [comment] 2015-08-23 23:25
I added a test case that shows that it can be done.
From looking at your code, it looks like you're just missing the CanSerialize method on the serializer.
That would explain why you're having trouble sending data over to the database.

**Comment by roryprimrose** [comment] 2015-08-25 03:25
Hmm, I'm still not seeing that in the fork. I updated InstantDeserializer to be 

```

        public class InstantDeserializer : DbObjectSerializer
        {
            public override bool CanDeserialize(Type sourceType, Type targetType)
            {
                return targetType == typeof(Instant);
            }

            public override bool CanSerialize(Type type, DbType dbType)
            {
                return type == typeof(Instant);
            }

            public override object SerializeObject(Type type, object o)
            {
                return ((Instant)o).ToDateTimeOffset();
            }

            public override object DeserializeObject(Type type, object o)
            {
                return Instant.FromDateTimeOffset((DateTimeOffset)o);
            }
        }
```

The test still failed. In fact, I didn't even hit any breakpoints on the serializer. The test output was:

```
System.InvalidCastException : Specified cast is not valid.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, ref Task task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, ref Task task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose(IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) in DBConnectionExtensions.cs: line 1459
   at Insight.Database.DBConnectionExtensions.Query(IDbConnection connection, String sql, Object parameters, IQueryReader`1 returns, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) in DBConnectionExtensions.cs: line 497
   at Insight.Database.DBConnectionExtensions.Query(IDbConnection connection, String sql, Object parameters, CommandType commandType, CommandBehavior commandBehavior, Nullable`1 commandTimeout, IDbTransaction transaction, Object outputParameters) in DBConnectionExtensions.generated.cs: line 51
   at Insight.Tests.CustomSerializationTests.CustomSerializerSupportsTableParameters() in SerializationTests.cs: line 101
```

**Comment by roryprimrose** [comment] 2015-08-25 03:26
I wasn't sure what type CanSerialize should expect so I also tried against DateTimeOffset and it had the same outcome.

**Comment by jonwagner** [comment] 2016-08-31 03:55
@roryprimrose can you repro this in a test case PR?

**Comment by roryprimrose** [comment] 2016-10-04 01:08
Sorry, I'm swamped ATM. I'll try to look at this sometime this week.

**Comment by roryprimrose** [comment] 2017-02-10 05:26
I can confirm that the serializer is used when returning values in a recordset and when converting object properties into parameters on the way in. 

The serialization error occurs when trying to provide a class instance to a procedure that uses a table type as a parameter. In this scenario the serializer does not seem to be used.

Current test scenario is at https://github.com/roryprimrose/Insight.Database/commit/90de786cbb9bc2061eb6bb327d921471f44cb919#diff-2f52ca27c1e4fcd767b2f41045a71ec8R111

**Comment by jonwagner** [comment] 2017-05-16 00:39
This is a duplicate of #292 - TVPs do not use customer serializers for ValueType objects. Will be fixing that soon.

**Closed by jonwagner** 2017-05-16 00:39 UTC
Labels: question
