### ISSUE TITLE
Auto-Open but not auto close

### ISSUE THREAD

**Issue by rokern002** [jonwagner/Insight.Database#389] opened 2018-12-18 10:41 UTC
Hi,
is it possible to configure insight database (6.2.8) have auto open connection but not close it?
I would like to use scoped injection in asp.net core 2.1 project on IDbConnection and  reuse the connection for the current request in my rest application (scope).

the goal is, let DI container to decide if element should be disposed or not.

```csharp

        private static IServiceCollection ConfigureDataAccess(this IServiceCollection services)
        {
            const string connectionStringName = "MySql";
            return services
                .AddScoped<IDbConnection>(a=> new MySqlConnection(a.GetService<IConfiguration>().GetConnectionString(connectionStringName)))
                .AddScoped<IUserRepository>(a=>a.GetService<IDbConnection>().As<IUserRepository>())
                //Another Repository
                ;
        }
```

**Comment by jonwagner** [comment] 2018-12-18 14:23
If your DI container opens the connection, then Insight will not close it. There is no close-only mode.

**Comment by rokern002** [comment] 2018-12-18 18:54
I really have to open connection on initialization (addscoped)? what if i have a service call before database access... the service result is invalid, but i already opened the connection even i no need one. kinda inefficient

**Comment by Jaxelr** [comment] 2018-12-19 01:04
Insight works by using an IDbConnection, if that connection is passed opened, it will remain open, if the connection is closed, insight will open/close it for you as explained on [the wiki](https://github.com/jonwagner/Insight.Database/wiki/Auto-Open) do you have a specific scenario where it doesnt work as intended? Feel free to post a sample.

**Comment by jonwagner** [comment] 2018-12-19 02:05
When we performance-tested the various modes, we found:

* Auto-open/close - retrieving connections from the connection pool had negligible overhead.
* Auto-open and hold open - keeping connections open longer than just retrieving data would cause the connection pool to hold open more connections than necessary, which made the system require additional connections, and then there was additional overhead for opening new connections.

Manual open/close is generally used when you have multiple database calls that you want to bind in a transaction.

The general MSFT advice is to rely on the connection pool to do its job, but if you're measuring actual performance problems you can easily write your own wrapper for the DbConnection and do your own open/close semantics.

**Comment by jonwagner** [comment] 2019-03-02 18:16
Closing due to inactivity.

**Closed by jonwagner** 2019-03-02 18:16 UTC
