### ISSUE TITLE
Complex data types

### ISSUE THREAD

**Issue by AndreiNeagu27** [jonwagner/Insight.Database#414] opened 2019-12-01 18:54 UTC
# Describe the feature

It would be great to have **more complex dataTypes** supported by this **_AMAZING_ ORM**!

## Is this feature related to a problem, describe

I was trying to use the SqlGeography dataType and Geography dataType in SqlServer, while trying to make an app the implements the Haversine formula. I kept getting the error _Unable to cast object of type 'System.DBNull' to type 'System.Type'._ and could not figure out, for the life of me, where was that comming from. So I cloned the repo, and looked at Insight.Database.Core.CodeGenerator.TypeConverterGenerator, that took me to the DbDataReaderWrapper ... unfortunaetly I could add the Microsoft.SqlServer.Type.dll so I could add the dataType myself.

## Additional context

If you need any help in implementing this feature, I would be more than happy to help!

10x!

**Comment by resnikb** [comment] 2019-12-03 00:57
@AndreiNeagu27 Hi Andrei, can you please share a minimal code sample that reproduces the issue?

**Comment by andymac4182** [comment] 2019-12-12 03:43
If there is actually a returned value does it work? Have you tried making the Property nullable?

**Comment by jonwagner** [comment] 2019-12-12 14:51
There was limited support for the sql server custom types in .NET Core 1.0/2.0 when we ported the code. As of right now, Sql Server custom types are only supported in .NET Framework builds.

If that has changed in recent sql server builds then it should be pretty easy to reenable that functionality.

**Comment by AndreiNeagu27** [comment] 2019-12-12 16:44
Hi guys!

So it's a .NET Framework build. I just have a crazy period right now. By the end of next week I will have a working example of the error (huh, that sounds weird) as @resnikb  requested.

Sorry for the late replies!

**Comment by Jaxelr** [comment] 2020-02-29 12:55
This is the open [issue on sqlclient](https://github.com/dotnet/SqlClient/issues/30)  that tracks this feature.

**Comment by jonwagner** [comment] 2020-05-24 16:12
This is a duplicate of #418 - we will track the custom sql types in that issue.

Note that custom sql types work properly in `net4x` implementations.

**Closed by jonwagner** 2020-05-24 16:12 UTC
