### ISSUE TITLE
sql transaction not working after updating to .Net core 3.1 with InsightDb

### ISSUE THREAD

**Issue by shahzain** [jonwagner/Insight.Database#445] opened 2020-09-25 07:06 UTC
# Describe the question

I needed to execute some stored procs in transactions using insightDb, I did the following and it was working fine with .net Core 2.2

        using (var ts = TransactionScopeBuilder.CreateReadCommitted())
         {
             await _profile.createProfile(user);
             await _profile.addAdditionalData(user);
             ts.Complete();
         }
After updating to .net core 3.1. I am getting this exception on createProfile(user). I am using insightDb and createProfile is the name of stored procedure being called. It was working fine on .net core 2.2. Here are all the details of exception.

InsightDb version is 6.3.1.

## Steps to reproduce (if applicable)
![image](https://user-images.githubusercontent.com/10272777/94236807-3cf94d00-ff27-11ea-86d3-653ae94e51f4.png)

After updating to .net core 3.1. I am getting this exception on createProfile(user). I am using insightDb and createProfile is the name of stored procedure being called. It was working fine on .net core 2.2. Here are all the details of exception.
InsightDb version is 6.3.1

Exception: On createProfile call I get following exception:

![image](https://user-images.githubusercontent.com/10272777/94236935-7336cc80-ff27-11ea-8337-5f846977a733.png)

![image](https://user-images.githubusercontent.com/10272777/94236988-919cc800-ff27-11ea-85d0-6e1e85a26c2c.png)

SerializationStackTraceString: Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.ConfigureExceptionTelemetry(DependencyTelemetry telemetry, Exception exception, PropertyFetcher numberFetcher)

Source: Microsoft.AI.DependencyCollector

StackTrace Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.ConfigureExceptionTelemetry(DependencyTelemetry telemetry, Exception exception, PropertyFetcher numberFetcher

_message
"Object reference not set to an instance of an object."

**Comment by jonwagner** [comment] 2020-09-25 17:30
The stack trace seems to indicate a problem with Microsoft's Application Insights. I would try disabling that first.

If that doesn't solve the problem, the next thing to check would be to remove the ambient transaction from your code. It's possible that .net has changed implementations between 2.2 and 3.1.

Finally, if neither of those reveals more information, please post the source code for the _profile object and how it is created.

**Comment by shahzain** [comment] 2020-09-26 02:12
upon removing TransactionScopeBuilder.CreateReadCommitted(), the procedure calls runs fine. But I need to run those sp's in a transaction.

_profile object is created the same as the following way:

![image](https://user-images.githubusercontent.com/10272777/94327888-8a2cfb80-ffc7-11ea-8aac-e90d3cc9aa06.png)

**Comment by jonwagner** [comment] 2020-10-14 14:07
Your stack trace points to this function in .net core:

```
        private static void ConfigureExceptionTelemetry(DependencyTelemetry telemetry, Exception exception)
        {
            telemetry.Success = false;
            telemetry.Properties["Exception"] = exception.ToInvariantString();

            var sqlException = exception as SqlException;

            if (sqlException != null)
            {
                telemetry.ResultCode = sqlException.Number.ToString(CultureInfo.InvariantCulture);
            }
        }
```

Nothing in here directly points to an interaction with InsightDB. Insight may be throwing an exception, but we can't see it with the Application Insights telemetry failure in the way.

If you would like additional assistance diagnosing the issue, please provide the following:

1. Remove Application Insights from your application and rerun the test.
2. Submit a complete stack trace, not a screenshot of the last frame.
3. Post a case that reproduces the problem with the minimum amount of code possible. Please don't point to sample code and say "it works like this." The sample code works, and your code does not, but we don't have your code, so we can't debug the problem. Either simplify your code so we can run it, or modify sample code so that it fails in the same way that your code fails.

I'd be happy to take a look again if you provide more information. I'll be doing another build soon so it would be good timing if a fix is needed.

**Comment by shahzain** [comment] 2020-10-16 03:31
@jonwagner, Thanks, we managed to do it without transaction now. But I will recreate this scenario for you and update you here.

**Comment by jonwagner** [comment] 2020-11-07 16:05
Another thought here... I'm not sure how TransactionScope works with async methods. I'm assuming that .net will restore the scope properly. It's possible that the missing calls to `ConfigureAwait` could have been an issue here. Those should be fixed in 6.3.2. Give that a try and see if there's an impact.

**Comment by resnikb** [comment] 2020-11-07 21:35
@shahzain How is your `TransactionScopeBuilder.CreateReadCommitted` implemented? In order to use `await` within the scope, you need to ensure that `TransactionScopeAsyncFlowOption.Enabled` is passed to `TransactionScope` constructor. Otherwise, async operations will not see the ambient transaction.

**Comment by shahzain** [comment] 2020-11-11 03:18
Thanks @jonwagner , @resnikb , I will add TransactionScopeAsyncFlowOption.Enabled. I think this was the problem.

**Comment by shahzain** [comment] 2020-11-12 08:00
@resnikb , The solution dd not worked.

![Uploading image.png…]()

**Comment by shahzain** [comment] 2020-11-12 08:01
@resnikb , The solution did not worked.

![image](https://user-images.githubusercontent.com/10272777/98911908-3038b480-24e7-11eb-915d-8956aa42e1ab.png)

**Comment by resnikb** [comment] 2020-11-12 14:31
Interesting - `TransactionScopeAsyncFlowOption.Enabled` is definitely a requirement to enable correct support for transactions when using asynchronous operations, but the exception seems to happen inside `Microsoft.AI.DependencyCollector` source. 

Looking at the [source code where the exception happens](https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/SqlClientDiagnostics/SqlClientDiagnosticSourceListener.cs), there doesn't seem to be much that could cause this - and one thing that could is already in a `try/catch` block.

This makes me think that perhaps you are using an older version of the `Microsoft.AI.DependencyCollector` package, which doesn't handle these exceptions?

**Comment by jonwagner** [comment] 2020-11-22 16:04
@shahzain I added a test case to illustrate that Insight properly handles asynchronous ambient transactions.

It appears that your code is not using `TransactionScopeAsyncFlowOption.Enabled` when creating the TransactionScope. That should fix your problem.

As for the `NullReferenceException` - that looks like ApplicationInsights is hiding the true exception. We cannot help you with that issue.

See: https://github.com/jonwagner/Insight.Database/blob/main/Insight.Tests/AsyncMiscTests.cs

(Side note - System.Data.SqlClient 4.4 does not support ambient transactions in dotnet core, so I updated the required version to 4.5 in the next build of Insight. If you receive the exception `Cannot enlists in ambient transaction` then make sure you are on version 4.5 or later.)

Closing this as resolved, but if you can modify the test case to fail, we can look at that issue.

**Closed by jonwagner** 2020-11-22 16:04 UTC
